// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutritionDiary.Infrastructure;

#nullable disable

namespace NutritionDiary.Infrastructure.Migrations
{
    [DbContext(typeof(NutritionDbContext))]
    partial class NutritionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NutritionDiary.Domain.Entities.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("FoodItemId")
                        .HasColumnType("integer");

                    b.Property<string>("FoodItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Meal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("QuantityInG")
                        .HasColumnType("double precision");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.ToTable("DiaryEntries");
                });

            modelBuilder.Entity("NutritionDiary.Domain.Entities.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FoodItems", (string)null);

                    b.HasDiscriminator<string>("ItemType").HasValue("FoodItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NutritionDiary.Domain.Entities.Product", b =>
                {
                    b.HasBaseType("NutritionDiary.Domain.Entities.FoodItem");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("NutriscoreGrade")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Product");
                });

            modelBuilder.Entity("NutritionDiary.Domain.Entities.DiaryEntry", b =>
                {
                    b.HasOne("NutritionDiary.Domain.Entities.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("NutritionDiary.Domain.ValueObjects.NutritionTotals", "NutritionTotalsSnapshot", b1 =>
                        {
                            b1.Property<int>("DiaryEntryId")
                                .HasColumnType("integer");

                            b1.Property<double?>("Calcium")
                                .HasColumnType("double precision");

                            b1.Property<double>("Carbohydrates")
                                .HasColumnType("double precision");

                            b1.Property<double>("EnergyKcal")
                                .HasColumnType("double precision");

                            b1.Property<double>("Fat")
                                .HasColumnType("double precision");

                            b1.Property<double>("Fiber")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Iron")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Potassium")
                                .HasColumnType("double precision");

                            b1.Property<double>("Proteins")
                                .HasColumnType("double precision");

                            b1.Property<double?>("Salt")
                                .HasColumnType("double precision");

                            b1.Property<double>("SaturatedFat")
                                .HasColumnType("double precision");

                            b1.Property<double>("Sugars")
                                .HasColumnType("double precision");

                            b1.Property<double?>("VitaminB12")
                                .HasColumnType("double precision");

                            b1.Property<double?>("VitaminC")
                                .HasColumnType("double precision");

                            b1.Property<double?>("VitaminD")
                                .HasColumnType("double precision");

                            b1.HasKey("DiaryEntryId");

                            b1.ToTable("DiaryEntries");

                            b1.WithOwner()
                                .HasForeignKey("DiaryEntryId");
                        });

                    b.Navigation("FoodItem");

                    b.Navigation("NutritionTotalsSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("NutritionDiary.Domain.Entities.FoodItem", b =>
                {
                    b.OwnsOne("NutritionDiary.Domain.ValueObjects.NutritionFacts", "NutritionFacts", b1 =>
                        {
                            b1.Property<int>("FoodItemId")
                                .HasColumnType("integer");

                            b1.Property<double?>("CalciumPer100g")
                                .HasColumnType("double precision");

                            b1.Property<double>("CarbohydratesPer100g")
                                .HasColumnType("double precision");

                            b1.Property<double>("EnergyKcalPer100g")
                                .HasColumnType("double precision");

                            b1.Property<double>("FatPer100g")
                                .HasColumnType("double precision");

                            b1.Property<double>("FiberPer100g")
                                .HasColumnType("double precision");

                            b1.Property<double?>("IronPer100g")
                                .HasColumnType("double precision");

                            b1.Property<double?>("PotassiumPer100g")
                                .HasColumnType("double precision");

                            b1.Property<double>("ProteinsPer100g")
                                .HasColumnType("double precision");

                            b1.Property<double?>("SaltPer100g")
                                .HasColumnType("double precision");

                            b1.Property<double>("SaturatedFatPer100g")
                                .HasColumnType("double precision");

                            b1.Property<double>("SugarsPer100g")
                                .HasColumnType("double precision");

                            b1.Property<double?>("VitaminB12Per100g")
                                .HasColumnType("double precision");

                            b1.Property<double?>("VitaminCPer100g")
                                .HasColumnType("double precision");

                            b1.Property<double?>("VitaminDPer100g")
                                .HasColumnType("double precision");

                            b1.HasKey("FoodItemId");

                            b1.ToTable("FoodItems");

                            b1.WithOwner()
                                .HasForeignKey("FoodItemId");
                        });

                    b.Navigation("NutritionFacts")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
